apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-server
  namespace: spire
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/spire-dev-spire-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-agent
  namespace: spire
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oidc-provider
  namespace: oidc-provider