apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-server-template
  namespace: spire
data:
  server.conf.template: |
    server {
      bind_address = "0.0.0.0"
      bind_port = "8081"
      trust_domain = "example.org"
      data_dir = "/run/spire/server/data"
      log_level = "DEBUG"
      default_x509_svid_ttl = "24h"
      ca_ttl = "48h"
      ca_subject = {
        country = ["US"]
        organization = ["Example Organization"]
        common_name = "example.org"
      }
      ca_key_type = "rsa-2048"
      jwt_issuer = "https://db-iam-auth-dev-spire-bundle.s3.us-east-1.amazonaws.com"
      federation {
        bundle_endpoint {
          address = "0.0.0.0"
          port = 8443
        }
      }
    }
    plugins {
      DataStore "sql" {
        plugin_data {
          database_type = "postgres"
          connection_string = "${DB_CONNECTION_STRING}"
        }
      }
      NodeAttestor "k8s_psat" {
        plugin_data {
          clusters = {
            "spire-demo" = {
              service_account_allow_list = ["spire:spire-agent", "spire:oidc-provider"]
            }
          }
        }
      }
      UpstreamAuthority "disk" {
        plugin_data {
          cert_file_path = "/opt/spire/ca/ca.crt"
          key_file_path = "/opt/spire/ca/ca.key"
        }
      }
      KeyManager "memory" {
      }
      Notifier "k8sbundle" {
        plugin_data {
          namespace = "spire"
        }
      }
      BundlePublisher "aws_s3" {
          plugin_data {
              region = "us-east-1"
              bucket = "spire-dev-spire-bundle"
              object_key = "keys"
              format = "jwks"
          }
      }
    }
    health_checks {
      listener_enabled = true
      bind_address = "0.0.0.0"
      bind_port = "8080"
      live_path = "/live"
      ready_path = "/ready"
    }