apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-agent
  namespace: spire
data:
  agent.conf: |
    agent {
      data_dir = "/run/spire"
      log_level = "DEBUG"
      server_address = "spire-server"
      server_port = "8081"
      socket_path = "/run/spire/agent-sockets/socket"
      trust_bundle_path = "/run/spire/bundle/bundle.crt"
      trust_domain = "example.org"
    
      admin_socket_path = "/run/spire/admin-socket/socket"
      authorized_delegates = [
        "spiffe://example.org/ns/csi/sa/spire-csi-provider"
      ]
    }

    plugins {
      NodeAttestor "k8s_psat" {
        plugin_data {
          cluster = "spire-demo"
        }
      }

      KeyManager "memory" {
        plugin_data = {}
      }

      WorkloadAttestor "k8s" {
        plugin_data {
          skip_kubelet_verification = true
        }
      }

      WorkloadAttestor "unix" {
        plugin_data = {}
      }
    }